# Generated by Django 6.0.5 on 2026-06-20 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-review_opened', '-submitted_at'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='review_closes_at',
            field=models.DateTimeField(blank=True, help_text='Planned end of the review/voting period — used for noble reminders.', null=True),
        ),
        migrations.CreateModel(
            name='VoteIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(blank=True, choices=[('', 'Undecided'), ('Village', 'Village'), ('Clave', 'Clave'), ('Kingdom', 'Kingdom'), ('Aisling', 'Aisling'), ('No Award', 'No Award')], default='', max_length=20)),
                ('review_text', models.TextField(blank=True, help_text='Draft review to copy-paste into the in-game Contest Hall.')),
                ('remind_before_close', models.BooleanField(default=False, help_text='Email this noble before the review period ends.')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_intentions', to='api.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_intentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'entry')},
            },
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
