# Generated by Django 6.0.5 on 2026-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Show this work in the Archive (older submissions) instead of the live board.'),
        ),
    ]
