# Generated by Django 6.0.5 on 2026-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entry_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='work_subject',
            field=models.CharField(choices=[('Art', 'Art'), ('Literature', 'Literature'), ('Lore', 'Lore'), ('Philosophy', 'Philosophy'), ('History', 'History'), ('Persona', 'Persona')], default='Literature', max_length=20),
        ),
    ]
